# This is a simple workflow to deploy a CDK stack

name: Deploy CDK Stack

on:
  push:
    branches: [ "main" ]

jobs:
  difference:
    name: Difference
    runs-on: ubuntu-latest
    steps:

    - name: Difference
      uses: ./.github/workflows.yml

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: difference
    steps:

    - name: Difference
      uses: ./.github/workflows.yml
    
    - name: Deploy
      run: |
        cdk deploy --require-approval=never
