# If Stack has difference, notify to slack

name: Check Stack Difference

on:
  pull_request:
    branches: [ "*" ]

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: cdk bootstrap
        id: bootstrap
        uses: youyo/aws-cdk-github-actions@v2.1.4
        with:
          cdk_subcommand: 'bootstrap'
          cdk_args: 'aws://117580903444/us-east-1'
          actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'

      - name: cdk diff
        id: diff
        uses: youyo/aws-cdk-github-actions@v2.1.4
        with:
          cdk_subcommand: 'diff'
          cdk_args: '--app "python app.py"'
          cdk_stack: 'my-static-website-stack'
          actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
