# If Stack has difference, notify to slack

name: Check Stack Difference

on:
  pull_request:
    branches: [ "*" ]

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: cdk bootstrap
        id: bootstrap
        run: |
          echo "::add-mask::$AWS_ACCOUNT_ID"
          cdk bootstrap aws://$AWS_ACCOUNT_ID/$AWS_DEFAULT_REGION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'

      - name: cdk diff
        id: diff
        uses: arnaskro/aws-cdk-v2-github-actions@v2.3.0
        with:
          cdk_subcommand: 'diff'
          cdk_args: '--app "python app.py"'
          cdk_stack: 'MyStaticSiteStack'
          actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'

      # https://github.com/marketplace/actions/action-slack
      - name: notify slack
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: GitHubActions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.diff.outputs.status_code == 1
